### ISSUE TITLE
where is the download link of data?

### ISSUE THREAD

**Issue by lucasjinreal** [icfaust/CATSAD#2]
where is the download link of data?

**Comment by icfaust** [comment]
You should be either able to clone the repo or download a zip using the green button on the main page of CATSAD (labeled code). The images are under /raw/. Unfortunately the .git file is large, but that is to be expected for the number of files.

**Comment by jinfagang** [comment]
@icfaust I can either saw any images inside git  repo (which actually a weired behavior stores data inside git) nor the CATSAD main page link.

I only saw the road mark symbol images.

**Comment by icfaust** [comment]
Hey @jinfagang sorry for the misunderstanding. You are right that it is a bit weird to have the data stored in the repo like this. However i felt like having the images fully in a repo like this would be more transparent and permanent and available in and out of China rather than downloading a random pan.baidu, dropbox or Google drive link. I hope you don't mind.
